### ISSUE TITLE
Update Preface to note CC-SA license and terms

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#107]

**Comment by aslakknutsen** [comment]
I'm guessing some standard O'Reilly copyright notice thingga-ma-jigg to protect front cover / logos etc will be included elsewhere?

**Comment by ALRubinger** [comment]
We're in production now, so any edits have to be made through them and not
into the Atlas repo.

Production will review and revise our stuff to their needs too.
