### ISSUE TITLE
chapter 7 @TransactionAttributeType.MANDATORY

### ISSUE THREAD

**Issue by yuxh** [arquillian/continuous-enterprise-development#126]
"The default for EJB is @TransactionAttributeType.MANDATORY, which creates a transaction if one is not already in flight."
I checked javeee6 ,it means"If there is no existing transaction, an exception is thrown. "

**Comment by robertpanzer** [comment]
Hmmm... Actually the default is REQUIRED, which creates a transaction if there is none yet.

**Comment by yuxh** [comment]
yes,it seems I checked the wrong part :),thank you .
