### ISSUE TITLE
First JPA Use Case

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#5]
Create the First JPA Use Case

**Comment by aslakknutsen** [comment]
https://github.com/arquillian/continuous-enterprise-development/blob/master/application/domain/relation/src/test/java/org/ced/domain/relation/test/RelationTestCase.java

**Comment by aslakknutsen** [comment]
https://github.com/arquillian/continuous-enterprise-development/pull/12

**Comment by ALRubinger** [comment]
Duplicate of #12
