### ISSUE TITLE
Mail T-Shirts to Contributors

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#61]
The first 5 reviewers/contributors get a T-shirt.  Currently we have:

@rreimann
@majson
@myfear
@mmatloka
@johnament

**Comment by ALRubinger** [comment]
OK:

@rreimann, @majson, @myfear, @mmatloka, @johnament...do you have any T-Shirt preferences?  Please email me your thoughts (and addresses) directly.

Options:  http://www.cafepress.com/jbossorg/7125835

S,
ALR

**Comment by johnament** [comment]
Need your email address, directly.

Though I may pick up that golf shirt.

**Comment by ALRubinger** [comment]
Late additions but worthy: @maniksurtani, @sannegrinovero

**Comment by ALRubinger** [comment]
Ordered for @rreimann, @mmatloka, @myfear, @johnament.  Others pending; please get me your info.

**Comment by rreimann** [comment]
Friendly reminder - Ike could probably ask santa to give him a lift to arrive in time for christmas ;-)

**Comment by ALRubinger** [comment]
@rreimann: Apologies, we did an order for the guys at JavaOne; I'm not finding your address and shirt preference email; could you point me to that or resend and I'll get it out to you ASAP? :)  Thanks!

**Comment by rreimann** [comment]
@ALRubinger Ike arrived today :-) Santas parcel service did a great job - thanks once again!

**Comment by mmatloka** [comment]
Btw what happens with mine?:)

**Comment by ALRubinger** [comment]
Mailed @mmatloka, thus closing.
