### ISSUE TITLE
Add linkname's to DAP overview in REST Chapter

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/continuous-enterprise-development#76]

**Comment by aslakknutsen** [comment]
Also remove the URI as defined in DAP on resources. The Link is the important part.

**Comment by ALRubinger** [comment]
I'm not sure what you mean here.  If this is a simple fix, issue a PR to your content and I'll review it?

**Comment by ALRubinger** [comment]
Oh, it's assigned to you anyway.  Good. :)
