### ISSUE TITLE
Chapter 6 - NoSQL: Data Grids and Graph Databases

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#80]

**Comment by ALRubinger** [comment]
Sending to @aslakknutsen for review before closing. Submitted upstream in master: 604fd9e688440d18f733e1c99afa4818a4807b6f

**Comment by aslakknutsen** [comment]
Added a few comments, sent back to @ALRubinger 

nice! :)

**Comment by aslakknutsen** [comment]
Minor fixes added. This https://github.com/arquillian/continuous-enterprise-development/commit/604fd9e688440d18f733e1c99afa4818a4807b6f#commitcomment-4116111 is still open. 

Should we keep them in there to show them all? Remove them to keep the source related to the above text? Split them up in two and add a new text description for the neo4j helpers ?
