### ISSUE TITLE
Update REST Chapter to account for code changes

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#81]
The following commit impacts the text in the REST Chapter:

a79d46f67b7b3277e47a05464ca5bdd6a50653b8

Update the prose to match.  Alternatively, describe for me what's changed and I'll handle the update, but I need at least some descriptive info to go off. :)

**Comment by aslakknutsen** [comment]
The commit message + javadoc on RESTInterceptorEnabler is not enough?

**Comment by ALRubinger** [comment]
Beautiful, yes.

**Comment by ALRubinger** [comment]
Reassigning to me.

**Comment by ALRubinger** [comment]
Reassigning to @aslakknutsen to verify 35a49a5.  Note: code changes are due to typo spelling correction.

**Comment by ALRubinger** [comment]
Ping for review/close @aslakknutsen

**Comment by aslakknutsen** [comment]
Added comments on the commit, reassign to @ALRubinger

**Comment by aslakknutsen** [comment]
Minor fixes pushed upstream.

One question remaining: https://github.com/arquillian/continuous-enterprise-development/commit/35a49a5d7b731e26c2aff1300c478ece7deadf8a#commitcomment-4115791
Do we keep it as is for simplicity or update it to sync with 'reality' ?

**Comment by aslakknutsen** [comment]
Agreed to leave as is for simplicity; https://github.com/arquillian/continuous-enterprise-development/commit/35a49a5d7b731e26c2aff1300c478ece7deadf8a#commitcomment-4863731

Closing
