### ISSUE TITLE
Add Application examples using PageObject/PageFragments functional tests

### ISSUE THREAD

**Issue by ALRubinger** [arquillian/continuous-enterprise-development#9]

**Comment by aslakknutsen** [comment]
https://github.com/arquillian/continuous-enterprise-development/blob/master/application/web/conference/src/test/java/org/ced/web/conference/test/ConferenceTestCase.java

**Comment by ALRubinger** [comment]
What's the status of this, and how does it relate to the JPA chapter?

**Comment by aslakknutsen** [comment]
It needs to be tied to the User Stories in a better way, but technically(tequnique) it does what it should. 

Working on a similar setup for REST.

**Comment by ALRubinger** [comment]
So which are the examples which bypass the DB?  Not in
domain/ConferenceTestCase?

**Comment by aslakknutsen** [comment]
The one you have there does. The Conference is created on Client side, pushed to Container vi Warp, then Produced by CDI as if it came from JPA

**Comment by aslakknutsen** [comment]
The old Graphene based tests ran out of date a long time ago as they were JSF based. 

https://github.com/arquillian/continuous-enterprise-development/commit/1dd78a29d77aa4ed8f31aec9fef4b3a111c29e69 contain new set of Graphene tests. See commit msg

**Comment by aslakknutsen** [comment]
This should now really just be incorporated in the UI chapter issue..?

**Comment by ALRubinger** [comment]
I believe this is now just in the UI chapter as Aslak notes.  Assigning to him for confirmation and close.

**Comment by aslakknutsen** [comment]
Correct. In UI Chapter, https://github.com/arquillian/continuous-enterprise-development/blob/master/Chapter10-UI.asciidoc
