### ISSUE TITLE
RESTinterceptorEnabler - phantom variable

### ISSUE THREAD

**Issue by johnament** [arquillian/continuous-enterprise-development#94]
In this code block:

```
@REST
@Interceptor
public class RESTInterceptorEnabler {

    @Inject
    private Instance<RESTInterceptor> instances;

    @AroundInvoke
    public Object intercept(final InvocationContext context) throws Exception {
        final List<RESTInterceptor> interceptors = sort(instances);
        InvocationContext wraped = new InvocationContext() {
            // Omitted for brevity
         }
        return wraped.proceed();

    }
...
}
```

The "wraped" (what does that even mean?) variable is never defined, as such as a reader with 0 knowledge about REST I have no clue what you're doing here.

**Comment by aslakknutsen** [comment]
``` java
InvocationContext wraped = new InovocationContext() {}
return wraped.proceed().
```

**Comment by johnament** [comment]
I'm blind.  Thank you.

Though, I think you should call it "wrapped" to be clearer.

**Comment by ALRubinger** [comment]
Still needs to be "wrapped", not "wraped".

**Comment by aslakknutsen** [comment]
Correct, the Code is fixed.. It'll be fixed in the example when ever you setup the auto import snippets.. :)

https://github.com/arquillian/continuous-enterprise-development/blob/master/code/application/web/rest/core/src/main/java/org/cedj/geekseek/web/rest/core/interceptor/RESTInterceptorEnabler.java

**Comment by ALRubinger** [comment]
Auto-import not gonna happen...too often I edit the code for the book text
to snip out irrelevant stuff or format differently for print. :)
